package cai.peter.directread.model;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

public class Group
{
	String name;
	Group parent;
	public Group(String name, Group parent)
	{
		super();
		this.name = name;
		this.parent = parent;
	}
	private List<Group>	groups = new ArrayList<Group>();
	List<Outline> outlines = new ArrayList<Outline>();
	
	public void addGroup( Group g)
	{
		groups.add(g);
	}
	
	public void addOutline( Outline o )
	{
		outlines.add(o);
	}
	
	public List<Group> getGroups()
	{
		return groups;
	}
	public void setGroups(List<Group> groups)
	{
		this.groups = groups;
	}
	public List<Outline> getOutlines()
	{
		return outlines;
	}
	public void setOutlines(List<Outline> outlines)
	{
		this.outlines = outlines;
	}
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	public Group getParent()
	{
		return parent;
	}
	public void setParent(Group parent)
	{
		this.parent = parent;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * @overwrite toString()
	 * @return String returns this object in a String
	 */
	public String toString()
	{
		StringBuilder sb = new StringBuilder();
		sb.append("Group::[");
		sb.append(" name:=");
		sb.append(name);
		sb.append(" parent:=");
		sb.append(parent);
//		sb.append(" groups:=");
//		sb.append(StringUtils.join(groups.toArray(),System.lineSeparator()));
		sb.append(" outlines:");
		sb.append(System.lineSeparator());
		sb.append(StringUtils.join(outlines.toArray(),System.lineSeparator()));
		sb.append(']');
		return sb.toString();
	}
}
